// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmN3WGr6KmYqgsHcfsyFs9104HoJ2RZwQ',
    appId: '1:66170276383:web:217ab5ce0976743ca3632a',
    messagingSenderId: '66170276383',
    projectId: 'sport-3f2f4',
    authDomain: 'sport-3f2f4.firebaseapp.com',
    storageBucket: 'sport-3f2f4.appspot.com',
    measurementId: 'G-VNE4S16823',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfVEQEaTsTxxojZmBaX91fBceTqi2Dmyc',
    appId: '1:66170276383:android:f8eb8d3724b7e98ca3632a',
    messagingSenderId: '66170276383',
    projectId: 'sport-3f2f4',
    storageBucket: 'sport-3f2f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi4QNVlVDleJJRt5T_6Ta-k9Sk-AKkT7w',
    appId: '1:66170276383:ios:f7cb17333fc8c898a3632a',
    messagingSenderId: '66170276383',
    projectId: 'sport-3f2f4',
    storageBucket: 'sport-3f2f4.appspot.com',
    iosClientId: '66170276383-lkvn9j9pemtdaqr0225m9ffv2c126lac.apps.googleusercontent.com',
    iosBundleId: 'com.example.sportifyv5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi4QNVlVDleJJRt5T_6Ta-k9Sk-AKkT7w',
    appId: '1:66170276383:ios:4879e6865da5e627a3632a',
    messagingSenderId: '66170276383',
    projectId: 'sport-3f2f4',
    storageBucket: 'sport-3f2f4.appspot.com',
    iosClientId: '66170276383-h2v7434p9i6eo2ubggrhr2882n36p8qn.apps.googleusercontent.com',
    iosBundleId: 'com.example.sportifyv5.RunnerTests',
  );
}
